### ISSUE TITLE
routes file

### ISSUE THREAD

**Issue by Shaun2D2** [mattstauffer/mergency#3]
Hey Matt,

Was thinking I could refactor the routes files and remove the closures to clean it up a bit and add some controllers, what do you think?

Shaun

**Comment by mattstauffer** [comment]
Honestly.. I actually like the whole app in the routes file. I know you can't use route caching that way, but being able to see the entire app in one place is really valuable for me.

Thanks, though, and thanks for asking! :)

**Comment by Shaun2D2** [comment]
no problem, it is my OCD kicking in ;P
